### ISSUE TITLE
Crear registro de productos

### ISSUE THREAD

**Issue by JcamiloSq** [JcamiloSq/Inventario#4]
Como usaurio necesito que se desarrolle un modulo con la funcionalidad para agregar, editar y eliminar productos del inventario.

Al crear
Incluir campos como código, descripción, precio y categoria es un id de relación a la tabla categorias.
En el listado mostrar estos mismo campos.

**Comment by JcamiloSq** [comment]
Añadir unidad de venta.

**Comment by JcamiloSq** [comment]
Después de un análisis identificamos que esta tarea es de tamaño XL.

**Comment by FrayJaramillo** [comment]
Crear un modulo para crear unidades de medida

**Comment by JcamiloSq** [comment]
Se requiere crear un modulo para controlar las unidades de medida para poder relacionarlas al producto. Se plantea crear una nueva incidencia para este nuevo proceso.
